'use strict';

const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const SAVE_KEY = 'nacre-save-v1';
const SAVE_BACKUP_KEY = `${SAVE_KEY}-backup`;
const SAVE_TEMP_KEY = `${SAVE_KEY}-temp`;

const GENERATORS = [
  { id:'firefly', name:'Luciole', icon:'✦', copy:'Une gardienne minuscule de la source.', cost:10, growth:1.15, rate:.2, unlock:0 },
  { id:'polyp', name:'Polype nacré', icon:'◌', copy:'Filtre l’ombre et relâche de la lueur.', cost:100, growth:1.16, rate:2, unlock:18 },
  { id:'anemone', name:'Anémone solaire', icon:'⌁', copy:'Transforme les courants en lumière vive.', cost:1200, growth:1.17, rate:18, unlock:240 },
  { id:'coral', name:'Jardin de corail', icon:'◇', copy:'Un récif autonome aux milliers de reflets.', cost:18000, growth:1.18, rate:150, unlock:3500 },
  { id:'whale', name:'Baleine astrale', icon:'◒', copy:'Porte un écosystème entier dans son sillage.', cost:420000, growth:1.19, rate:1800, unlock:75000 },
  { id:'moon', name:'Lune lagunaire', icon:'◐', copy:'Soulève chaque marée de la planète.', cost:12000000, growth:1.2, rate:24000, unlock:100000000 }
];
const MUTATIONS = [
  { id:'membrane', name:'Membrane prismatique', copy:'Les pulsations produisent 5× plus.', cost:8, era:1 },
  { id:'symbiosis', name:'Symbiose profonde', copy:'Toute la production est doublée.', cost:35, era:1 },
  { id:'dream', name:'Rêve collectif', copy:'La Résonance dure deux fois plus longtemps.', cost:120, era:2 },
  { id:'tide', name:'Marée intérieure', copy:'Les gains hors ligne passent à 85%.', cost:320, era:2 },
  { id:'cosmic', name:'Nacre cosmique', copy:'Chaque Perle de mémoire est 50% plus puissante.', cost:900, era:3 }
];
const NODES = [
  { id:'shoal', name:'Banc lumineux', icon:'•••', cost:100, mult:1.1, copy:'+10% de production' },
  { id:'current', name:'Courant chaud', icon:'≈', cost:600, mult:1.15, copy:'+15% de production' },
  { id:'trench', name:'Faille chantante', icon:'⌄', cost:3000, mult:1.2, copy:'+20% de production' },
  { id:'gyre', name:'Grand gyre', icon:'◉', cost:15000, mult:1.3, copy:'+30% de production' },
  { id:'moonpool', name:'Puits de lune', icon:'◐', cost:65000, mult:1.4, copy:'+40% de production' },
  { id:'mind', name:'Esprit océan', icon:'✧', cost:250000, mult:1.5, copy:'+50% de production' }
];
const ERAS = [
  { name:'Étincelle', start:0, end:25000, next:'Éveiller la colonie' },
  { name:'Colonie', start:25000, end:1000000000, next:'Former le grand récif' },
  { name:'Récif', start:1000000000, end:1000000000000, next:'Éveiller la planète' },
  { name:'Planète vivante', start:1000000000000, end:1e16, next:'Composer une mémoire éternelle' }
];

function freshState() {
  return { schemaVersion:1, savedAt:Date.now(), lumen:0, runLifetime:0, allTimeLumen:0,
    generators:Object.fromEntries(GENERATORS.map(g=>[g.id,0])), insight:0, vitality:0, memories:0, prestigeCount:0,
    mutations:[], nodes:[], allocation:{ light:70, insight:20, vitality:10 }, totalTaps:0, buyMode:1, resonanceUntil:0,
    settings:{ motion:true, haptics:true }, stats:{ startedAt:Date.now(), highestRate:0, offlineEarned:0 } };
}
function sanitise(data) {
  const base=freshState(); if (!data || typeof data!=='object') return base; const s={...base,...data};
  ['lumen','runLifetime','allTimeLumen','insight','vitality','memories','prestigeCount','totalTaps'].forEach(k=>s[k]=Number.isFinite(Number(s[k]))?Math.max(0,Number(s[k])):base[k]);
  s.generators={...base.generators,...(data.generators||{})}; GENERATORS.forEach(g=>{const value=Number(s.generators[g.id]);s.generators[g.id]=Number.isFinite(value)?Math.max(0,Math.floor(value)):0});
  s.mutations=Array.isArray(data.mutations)?data.mutations.filter(id=>MUTATIONS.some(m=>m.id===id)):[]; s.nodes=Array.isArray(data.nodes)?data.nodes.filter(id=>NODES.some(n=>n.id===id)):[];
  s.settings={ motion:data.settings?.motion!==false, haptics:data.settings?.haptics!==false };
  s.stats={...base.stats}; ['startedAt','highestRate','offlineEarned'].forEach(k=>{const value=Number(data.stats?.[k]);if(Number.isFinite(value))s.stats[k]=Math.max(0,value)});
  const rawAllocation={...base.allocation,...(data.allocation||{})}; Object.keys(rawAllocation).forEach(k=>{const value=Number(rawAllocation[k]);rawAllocation[k]=Number.isFinite(value)?Math.max(0,Math.min(100,Math.round(value))):base.allocation[k]});
  const allocationTotal=rawAllocation.light+rawAllocation.insight+rawAllocation.vitality; s.allocation=allocationTotal>0?{light:Math.round(rawAllocation.light/allocationTotal*100),insight:0,vitality:0}:{...base.allocation};if(allocationTotal>0){s.allocation.insight=Math.min(100-s.allocation.light,Math.round(rawAllocation.insight/allocationTotal*100));s.allocation.vitality=100-s.allocation.light-s.allocation.insight}
  s.buyMode=data.buyMode==='max'?'max':([1,10].includes(Number(data.buyMode))?Number(data.buyMode):1); s.savedAt=Number.isFinite(Number(data.savedAt))?Math.max(0,Number(data.savedAt)):Date.now(); s.resonanceUntil=Number.isFinite(Number(data.resonanceUntil))?Math.max(0,Number(data.resonanceUntil)):0; return s;
}
function load() { for (const key of [SAVE_KEY,SAVE_BACKUP_KEY]) try { const raw=localStorage.getItem(key); if(raw) return sanitise(JSON.parse(raw)); } catch {} return freshState(); }
let state=load(), tapTimes=[], lastFrame=performance.now(), lastRender=0, lastSave=Date.now(), knownEra=getEra();
function save() { state.savedAt=Date.now(); const text=JSON.stringify(state); try { localStorage.setItem(SAVE_TEMP_KEY,text); const old=localStorage.getItem(SAVE_KEY); if(old)localStorage.setItem(SAVE_BACKUP_KEY,old); localStorage.setItem(SAVE_KEY,localStorage.getItem(SAVE_TEMP_KEY)); localStorage.removeItem(SAVE_TEMP_KEY); } catch { toast('Sauvegarde locale indisponible'); } lastSave=Date.now(); }
function format(n, precise=false) { if(!Number.isFinite(n))return '∞'; for(const [v,u] of [[1e15,'Qa'],[1e12,'T'],[1e9,'Md'],[1e6,'M'],[1e3,'k']])if(Math.abs(n)>=v)return `${(n/v).toLocaleString('fr-FR',{maximumFractionDigits:precise?2:1})} ${u}`; return n.toLocaleString('fr-FR',{maximumFractionDigits:precise||Math.abs(n)<100?1:0}); }
function getEra(){return state.runLifetime>=1e12&&state.nodes.length===NODES.length?3:state.runLifetime>=1e9?2:state.runLifetime>=25000?1:0}
function milestone(n){let m=1;if(n>=10)m*=2;if(n>=25)m*=2;if(n>=50)m*=3;if(n>=100)m*=5;return m}
function globalMult(){let m=1+state.memories*(state.mutations.includes('cosmic')?.225:.15);if(state.mutations.includes('symbiosis'))m*=2;NODES.forEach(n=>{if(state.nodes.includes(n.id))m*=n.mult});if(Date.now()<state.resonanceUntil)m*=3;if(getEra()>=1){m*=.45+state.allocation.light/70;m*=1+Math.log10(1+state.vitality)*.08}return m}
function baseRate(){return GENERATORS.reduce((sum,g)=>sum+state.generators[g.id]*g.rate*milestone(state.generators[g.id]),0)}
function rate(){return baseRate()*globalMult()}
function tapYield(){let n=Math.max(1,Math.sqrt(rate()+1)*.4);if(state.mutations.includes('membrane'))n*=5;return n*(1+state.memories*.1)}
function cost(g,amount=1){const owned=state.generators[g.id],n=Number(amount);return g.cost*Math.pow(g.growth,owned)*(Math.pow(g.growth,n)-1)/(g.growth-1)}
function maxBuy(g){const x=1+state.lumen*(g.growth-1)/(g.cost*Math.pow(g.growth,state.generators[g.id]));return Math.max(0,Math.floor(Math.log(Math.max(1,x))/Math.log(g.growth)))}
function addLumen(n){state.lumen+=n;state.runLifetime+=n;state.allTimeLumen+=n}
function haptic(p){if(state.settings.haptics&&navigator.vibrate)navigator.vibrate(p)}
function toast(text){const n=document.createElement('div');n.className='toast';n.textContent=text;$('#toast-region').append(n);setTimeout(()=>n.remove(),2600)}
function buyGenerator(id,forced){const g=GENERATORS.find(x=>x.id===id);if(!g||state.runLifetime<g.unlock)return false;const mode=forced||state.buyMode,amount=mode==='max'?maxBuy(g):Number(mode);if(amount<1)return false;const price=cost(g,amount);if(state.lumen+1e-9<price)return false;const before=state.generators[id];state.lumen-=price;state.generators[id]+=amount;[10,25,50,100].forEach(mark=>{if(before<mark&&state.generators[id]>=mark)toast(`${g.name} · palier ${mark} atteint`)});haptic(12);save();render(true);return true}
function pulse(event){const now=Date.now();tapTimes=tapTimes.filter(t=>now-t<10000);tapTimes.push(now);state.totalTaps++;const gain=tapYield();addLumen(gain);if(tapTimes.length>=20&&now>=state.resonanceUntil){state.resonanceUntil=now+(state.mutations.includes('dream')?30000:15000);tapTimes=[];toast('Résonance · production ×3');haptic([18,35,28])}if(event&&state.settings.motion){const n=document.createElement('span');n.className='float-gain';n.textContent=`+${format(gain,true)}`;n.style.left=`${event.clientX}px`;n.style.top=`${event.clientY}px`;document.body.append(n);setTimeout(()=>n.remove(),820)}$('#pulse-button').classList.add('pulsing');setTimeout(()=>$('#pulse-button').classList.remove('pulsing'),100);haptic(5);render()}
function economy(seconds){const r=rate();addLumen(r*seconds);if(getEra()>=1){const root=Math.sqrt(baseRate());state.insight+=root*state.allocation.insight/100*.025*seconds;state.vitality+=root*state.allocation.vitality/100*.012*seconds}state.stats.highestRate=Math.max(state.stats.highestRate,r);const era=getEra();if(era>knownEra){knownEra=era;toast(`Nouvelle ère · ${ERAS[era].name}`);haptic([25,45,25,45,50]);save()}}
function recommendation(){return GENERATORS.filter(g=>state.runLifetime>=g.unlock).reduce((best,g)=>{const score=cost(g)/(g.rate*milestone(state.generators[g.id]));return!best||score<best.score?{g,score}:best},null)?.g||GENERATORS[0]}

function renderGenerators(){ $('#generator-list').innerHTML=GENERATORS.map(g=>{const unlocked=state.runLifetime>=g.unlock,amount=state.buyMode==='max'?maxBuy(g):Number(state.buyMode),price=cost(g,Math.max(1,amount)),owned=state.generators[g.id],output=owned*g.rate*milestone(owned)*globalMult();return `<article class="generator-card ${unlocked?'':'locked'}"><div class="gen-icon">${unlocked?g.icon:'·'}</div><div class="gen-copy"><h3>${unlocked?g.name:'Espèce inconnue'} <span class="gen-count">${unlocked?owned:''}</span></h3><p>${unlocked?`${g.copy}<br>${format(output,true)} /s`:`Découverte à ${format(g.unlock)} lueurs`}</p></div><button class="gen-buy" data-buy="${g.id}" ${!unlocked||amount<1||state.lumen<price?'disabled':''}>${amount>0?`+${amount}`:'—'}<small>${format(price)}</small></button></article>`}).join('');$$('[data-buy]').forEach(b=>b.onclick=()=>buyGenerator(b.dataset.buy)) }
function setAllocation(key,value){const others=Object.keys(state.allocation).filter(k=>k!==key),rest=100-value,sum=state.allocation[others[0]]+state.allocation[others[1]];state.allocation[key]=value;if(!sum){state.allocation[others[0]]=rest;state.allocation[others[1]]=0}else{state.allocation[others[0]]=Math.round(rest*state.allocation[others[0]]/sum);state.allocation[others[1]]=rest-state.allocation[others[0]]}renderReef()}
function buyNode(id){const n=NODES.find(x=>x.id===id);if(!n||state.nodes.includes(id)||state.insight<n.cost)return;state.insight-=n.cost;state.nodes.push(id);toast(`${n.name} relié`);save();render(true)}
function renderReef(){const era=getEra();if(!era){$('#reef-content').className='locked-panel';$('#reef-content').innerHTML=`<div class="big-lock">◇</div><h3>Un monde cherche son équilibre</h3><p>Produisez ${format(25000)} lueurs pour former la première colonie.</p>`;return}$('#reef-content').className='';const rows=[['light','Photosynthèse','Amplifie la production de lueur'],['insight','Exploration','Crée de l’intuition pour muter'],['vitality','Symbiose','La vitalité amplifie progressivement tout le récif']].map(([id,name,copy])=>`<label class="allocation-row"><span><strong>${name}</strong><small>${copy}</small></span><b>${state.allocation[id]}%</b><input type="range" min="0" max="100" value="${state.allocation[id]}" data-allocation="${id}"></label>`).join('');const network=era>=2?`<article class="panel-card"><span class="eyebrow">RÉSEAU DU RÉCIF</span><h3>Relier les grands courants</h3><p>Chaque nœud transforme durablement la production.</p><div class="node-grid">${NODES.map((n,i)=>{const bought=state.nodes.includes(n.id),available=!i||state.nodes.includes(NODES[i-1].id);return`<button class="reef-node ${bought?'bought':''}" data-node="${n.id}" ${bought||!available||state.insight<n.cost?'disabled':''}><i>${n.icon}</i><strong>${n.name}</strong><small>${bought?n.copy:`${n.cost} intuition`}</small></button>`}).join('')}</div></article>`:`<article class="locked-panel inline-lock"><strong>Le grand récif dort encore</strong><span>${format(Math.max(0,1e9-state.runLifetime))} lueurs avant son éveil</span></article>`;$('#reef-content').innerHTML=`<article class="panel-card"><div class="resource-pair"><span><small>Intuition</small><strong>${format(state.insight,true)}</strong></span><span><small>Vitalité</small><strong>${format(state.vitality,true)}</strong></span></div><h3>Orienter les courants</h3><p>La somme reste égale à 100%. Les autres courants s’adaptent.</p>${rows}</article>${network}`;$$('[data-allocation]').forEach(i=>i.oninput=()=>setAllocation(i.dataset.allocation,Number(i.value)));$$('[data-node]').forEach(b=>b.onclick=()=>buyNode(b.dataset.node))}
function buyMutation(id){const m=MUTATIONS.find(x=>x.id===id);if(!m||state.mutations.includes(id)||getEra()<m.era||state.insight<m.cost)return;state.insight-=m.cost;state.mutations.push(id);toast(`${m.name} acquise`);save();render(true)}
function prestige(){const gain=Math.floor(Math.sqrt(state.runLifetime/1e12));if(gain<1||getEra()<3||!confirm(`Faire renaître l’océan et recevoir ${gain} Perle${gain>1?'s':''} de mémoire ?`))return;const keep={memories:state.memories+gain,prestigeCount:state.prestigeCount+1,allTimeLumen:state.allTimeLumen,settings:state.settings,stats:state.stats,mutations:state.mutations.filter(id=>id==='cosmic')};state={...freshState(),...keep};knownEra=0;save();switchTab('source');toast('Un nouvel océan s’éveille');render(true)}
function renderEvolution(){const era=getEra(),gain=Math.floor(Math.sqrt(state.runLifetime/1e12));const mutations=MUTATIONS.map(m=>{const bought=state.mutations.includes(m.id),available=era>=m.era;return`<button class="mutation-card ${bought?'bought':''}" data-mutation="${m.id}" ${bought||!available||state.insight<m.cost?'disabled':''}><span>${bought?'✓':'✦'}</span><div><strong>${m.name}</strong><small>${available?m.copy:`Disponible à l’ère ${m.era+1}`}</small></div><b>${bought?'Acquise':`${m.cost} ◇`}</b></button>`}).join('');const install=!matchMedia('(display-mode: standalone)').matches&&!navigator.standalone&&state.totalTaps>20?`<article class="panel-card install-card"><span>＋</span><div><h3>Emportez Nacre</h3><p>Sur iPhone : Partager, puis « Sur l’écran d’accueil ».</p></div></article>`:'';const gate=state.runLifetime>=1e12&&state.nodes.length<NODES.length?`Reliez encore ${NODES.length-state.nodes.length} courant${NODES.length-state.nodes.length>1?'s':''} du récif pour éveiller la planète.`:`La planète doit produire encore ${format(Math.max(0,1e12-state.runLifetime))} lueurs avant de muer.`;$('#evolution-content').innerHTML=`${install}<article class="panel-card"><div class="resource-pair"><span><small>Perles de mémoire</small><strong>${format(state.memories)}</strong></span><span><small>Renaissances</small><strong>${state.prestigeCount}</strong></span></div><h3>Mutations</h3><p>L’intuition transforme les lois de votre océan.</p><div class="mutation-list">${mutations}</div></article><article class="panel-card prestige-card"><span class="eyebrow">RENAISSANCE</span><h3>Mue planétaire</h3><p>${era>=3?`Dissoudre ce monde pour obtenir <strong>${gain} ${gain>1?'Perles':'Perle'} de mémoire</strong>.`:gate}</p><button class="primary-wide" id="prestige-button" ${gain<1||era<3?'disabled':''}>Renaître avec ${gain} ◇</button></article><article class="panel-card"><h3>Trace de votre monde</h3><div class="stat-grid"><div class="stat"><strong>${format(state.allTimeLumen)}</strong><small>Lueurs créées</small></div><div class="stat"><strong>${format(state.stats.highestRate)}</strong><small>Record /s</small></div><div class="stat"><strong>${format(state.totalTaps)}</strong><small>Pulsations</small></div><div class="stat"><strong>${format(state.stats.offlineEarned)}</strong><small>Gains hors ligne</small></div></div></article>`;$$('[data-mutation]').forEach(b=>b.onclick=()=>buyMutation(b.dataset.mutation));$('#prestige-button').onclick=prestige}

function render(force=false){const eraIndex=getEra(),era=ERAS[eraIndex],r=rate();$('#lumen-display').textContent=format(state.lumen);$('#rate-display').textContent=`${format(r,true)} / seconde`;$('#era-label').textContent=`ÈRE ${['I','II','III','IV'][eraIndex]} · ${era.name.toUpperCase()}`;const progress=eraIndex===3?Math.min(100,Math.log10(Math.max(1,state.runLifetime/era.start))*25):Math.min(100,(state.runLifetime-era.start)/(era.end-era.start)*100);$('#era-progress').style.width=`${Math.max(0,progress)}%`;const reefGate=eraIndex===2&&state.runLifetime>=era.end&&state.nodes.length<NODES.length;$('#next-label').textContent=reefGate?'Relier tous les grands courants':era.next;$('#next-value').textContent=reefGate?`${state.nodes.length} / ${NODES.length}`:format(Math.max(0,era.end-state.runLifetime));$('#tap-value').textContent=`+${format(tapYield(),true)}`;const active=Date.now()<state.resonanceUntil,resProgress=active?Math.max(0,(state.resonanceUntil-Date.now())/(state.mutations.includes('dream')?30000:15000)*100):Math.min(100,tapTimes.length*5);$('#resonance-label').textContent=active?`Résonance ×3 · ${Math.ceil((state.resonanceUntil-Date.now())/1000)}s`:`Résonance ${Math.floor(resProgress)}%`;$('#resonance-bar').style.width=`${resProgress}%`;const pick=recommendation(),price=cost(pick);$('#focus-title').textContent=`Faire naître : ${pick.name}`;$('#focus-copy').textContent=`${format(pick.rate*globalMult(),true)} lueurs par seconde. Vous en avez ${state.generators[pick.id]}.`;$('#focus-cost').textContent=format(price);$('#focus-action').disabled=state.lumen<price;$('#focus-action').dataset.generator=pick.id;$('#reef-lock').hidden=eraIndex>=1;if(force||$('#view-life').classList.contains('active'))renderGenerators();if(force||$('#view-reef').classList.contains('active'))renderReef();if(force||$('#view-evolution').classList.contains('active'))renderEvolution()}
function switchTab(tab){$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$$('.view').forEach(v=>{const on=v.dataset.view===tab;v.hidden=!on;v.classList.toggle('active',on)});if(tab==='life')renderGenerators();if(tab==='reef')renderReef();if(tab==='evolution')renderEvolution();scrollTo({top:0,behavior:state.settings.motion?'smooth':'auto'})}
function resumeOffline(){const seconds=Math.max(0,Math.min(28800,(Date.now()-Number(state.savedAt||Date.now()))/1000));if(seconds<30)return;const efficiency=state.mutations.includes('tide')?.85:.65,gain=rate()*seconds*efficiency;if(gain<=0)return;addLumen(gain);state.stats.offlineEarned+=gain;const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60);$('#offline-copy').innerHTML=`Pendant ${h?`${h} h `:''}${m} min, votre récif a recueilli <strong>${format(gain)} lueurs</strong> à ${Math.round(efficiency*100)}% d’efficacité.`;$('#offline-dialog').showModal();save()}
function exportSave(){save();const text=btoa(unescape(encodeURIComponent(JSON.stringify(state))));if(navigator.clipboard?.writeText)navigator.clipboard.writeText(text).then(()=>toast('Sauvegarde copiée')).catch(()=>prompt('Copiez votre sauvegarde :',text));else prompt('Copiez votre sauvegarde :',text)}
function importSave(){const text=prompt('Collez votre sauvegarde Nacre :');if(!text)return;try{state=sanitise(JSON.parse(decodeURIComponent(escape(atob(text.trim())))));knownEra=getEra();save();render(true);toast('Sauvegarde restaurée')}catch{toast('Cette sauvegarde est illisible')}}
function loop(now){const delta=Math.min(1,Math.max(0,(now-lastFrame)/1000));lastFrame=now;economy(delta);if(now-lastRender>180){render();lastRender=now}if(Date.now()-lastSave>10000)save();requestAnimationFrame(loop)}

$('#pulse-button').onpointerdown=pulse;$('#focus-action').onclick=()=>buyGenerator($('#focus-action').dataset.generator,1);$$('[data-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$$('[data-buy-mode]').forEach(b=>b.onclick=()=>{state.buyMode=b.dataset.buyMode==='max'?'max':Number(b.dataset.buyMode);$$('[data-buy-mode]').forEach(x=>x.classList.toggle('active',x===b));renderGenerators()});$('#settings-button').onclick=()=>$('#settings-dialog').showModal();$('#motion-toggle').checked=state.settings.motion;$('#haptics-toggle').checked=state.settings.haptics;document.body.classList.toggle('reduced-motion',!state.settings.motion);$('#motion-toggle').onchange=e=>{state.settings.motion=e.target.checked;document.body.classList.toggle('reduced-motion',!e.target.checked);save()};$('#haptics-toggle').onchange=e=>{state.settings.haptics=e.target.checked;save()};$('#export-button').onclick=exportSave;$('#import-button').onclick=importSave;$('#reset-button').onclick=()=>{if(confirm('Effacer toute votre progression, y compris les Perles de mémoire ?')){localStorage.removeItem(SAVE_KEY);localStorage.removeItem(SAVE_BACKUP_KEY);state=freshState();save();location.reload()}};document.addEventListener('visibilitychange',()=>{if(document.hidden)save();else{resumeOffline();lastFrame=performance.now()}});addEventListener('pagehide',save);
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
async function registerWebMCP(){if(!navigator.modelContext?.registerTool)return;const tools=[{name:'nacre_state',description:'Lire la progression actuelle du jeu Nacre.',inputSchema:{type:'object',properties:{}},execute:async()=>({content:[{type:'text',text:JSON.stringify({era:ERAS[getEra()].name,lumen:state.lumen,rate:rate(),insight:state.insight,memories:state.memories})}]})},{name:'nacre_pulse',description:'Déclencher une pulsation dans Nacre.',inputSchema:{type:'object',properties:{}},execute:async()=>{pulse();return{content:[{type:'text',text:`Pulsation effectuée. ${format(state.lumen)} lueurs.`}]} }},{name:'nacre_buy',description:'Acheter un producteur dans Nacre.',inputSchema:{type:'object',properties:{id:{type:'string',enum:GENERATORS.map(g=>g.id)}},required:['id']},execute:async({id})=>({content:[{type:'text',text:buyGenerator(id,1)?'Achat effectué.':'Achat impossible.'}]})}];for(const tool of tools)try{await navigator.modelContext.registerTool(tool)}catch{}}
render(true);resumeOffline();registerWebMCP();requestAnimationFrame(loop);
